Added links between entities
RustamBikiteev/ComponentSystem pull request #8
Opened 2023-05-17 15:59 UTC by TimKhasanov

2023-05-18 15:24 UTC, Rustam-Bikiteev commented on src/main/java/com/aston/componentsystem/model/Component.java
> +    @OneToMany(fetch = FetchType.EAGER, mappedBy = "componentId")
Тут я вижу либо OnetoOne, Либо ManyToOne, карта в любом случае одна, а в ней заменяется либо 1 компонент, либо несколько

2023-05-18 15:24 UTC, Rustam-Bikiteev commented on src/main/java/com/aston/componentsystem/model/Balance.java
> +    @ManyToOne(fetch = FetchType.EAGER,cascade = CascadeType.ALL)
С балансом та же история, по идее баланс же у нас 1 на всю авиакомпанию.

2023-05-18 15:24 UTC, Rustam-Bikiteev commented on src/main/java/com/aston/componentsystem/model/Component.java
> +    @OneToMany(fetch = FetchType.EAGER, mappedBy = "componentId")
Здесь обратная история, но баланс вроде бы 1 должен быть

2023-05-18 15:24 UTC, Rustam-Bikiteev commented on src/main/java/com/aston/componentsystem/model/Flight.java
> +    private List<Balance> balances;
обратная история, баланс - One

2023-05-18 15:24 UTC, Rustam-Bikiteev commented on src/main/java/com/aston/componentsystem/model/WorkCard.java
> +   @ManyToOne(fetch = FetchType.EAGER,cascade = CascadeType.ALL)
Обратная история, карта по отношению к компоненту, одна должна быть.

2023-05-18 16:21 UTC, PizzzaDog requested changes

2023-05-18 16:21 UTC, PizzzaDog commented on src/main/java/com/aston/componentsystem/model/Component.java
> +    @OneToMany(fetch = FetchType.EAGER, mappedBy = "componentId")
ManyToOne

2023-05-18 16:21 UTC, PizzzaDog commented on src/main/java/com/aston/componentsystem/model/Component.java
> +    @OneToMany(fetch = FetchType.EAGER, mappedBy = "componentId")
FetchType.EAGER опасен, посмотри @EntityGraph и всякие @Query

2023-05-18 16:21 UTC, PizzzaDog commented on src/main/java/com/aston/componentsystem/model/Component.java
Тут можно @NamedEntityGraph (name= GRAPH_GET_AIRCRAFT, и vlaue
И потом в репозитории
@EntityGraph

2023-05-18 16:21 UTC, PizzzaDog commented on src/main/java/com/aston/componentsystem/model/Aircraft.java
Lombok опционально

2023-05-18 16:21 UTC, PizzzaDog commented on src/main/java/com/aston/componentsystem/model/Component.java
> +    @OneToMany(fetch = FetchType.EAGER, mappedBy = "componentId")
Выпилить вообще. Максимум что может быть это Price

2023-05-18 16:21 UTC, PizzzaDog commented on src/main/java/com/aston/componentsystem/model/Flight.java
> +    private List<Balance> balances;
Убрать

2023-05-18 16:21 UTC, PizzzaDog commented on src/main/java/com/aston/componentsystem/model/Warehouse.java
> +    @OneToMany(fetch = FetchType.EAGER, mappedBy = "warehouse")
Советую посмотреть необходимость двусторонних связей, возможно не везде они нужны

2023-05-18 16:21 UTC, PizzzaDog commented on src/main/java/com/aston/componentsystem/model/Warehouse.java
> +    private List<Component> componentId;
List<Component> components?

2023-05-19 14:22 UTC, Rustam-Bikiteev approved these changes

2023-05-19 14:22 UTC, merged